// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrdEbNO2O3M450yZJyoVulwb2izEaqGg',
    appId: '1:529985962869:web:c6ce4c645e71eb5351093c',
    messagingSenderId: '529985962869',
    projectId: 'techspot-13310',
    authDomain: 'techspot-13310.firebaseapp.com',
    storageBucket: 'techspot-13310.appspot.com',
    measurementId: 'G-0JX8FTTRVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFA-w1-S6ayMmmVhB88WmqBKFvEaQRIzQ',
    appId: '1:529985962869:android:9cdd31d10b003f6751093c',
    messagingSenderId: '529985962869',
    projectId: 'techspot-13310',
    storageBucket: 'techspot-13310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXnJjtVeTqqDXviB-ht61v7-1Xw-jSwwI',
    appId: '1:529985962869:ios:7de9292871087b7351093c',
    messagingSenderId: '529985962869',
    projectId: 'techspot-13310',
    storageBucket: 'techspot-13310.appspot.com',
    iosClientId: '529985962869-h8rilrpikhe4p00n4dc6jpru5pvlnac4.apps.googleusercontent.com',
    iosBundleId: 'com.example.showcaseOfComputerComponents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXnJjtVeTqqDXviB-ht61v7-1Xw-jSwwI',
    appId: '1:529985962869:ios:7de9292871087b7351093c',
    messagingSenderId: '529985962869',
    projectId: 'techspot-13310',
    storageBucket: 'techspot-13310.appspot.com',
    iosClientId: '529985962869-h8rilrpikhe4p00n4dc6jpru5pvlnac4.apps.googleusercontent.com',
    iosBundleId: 'com.example.showcaseOfComputerComponents',
  );
}
